server:
  port: 8092

spring:
  application:
    name: project-enterprise-rag
  ai:
    openai:
      api-key: ${AI_API_KEY:demo-key}
      base-url: ${AI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${AI_CHAT_MODEL:gpt-4o-mini}
      embedding:
        options:
          model: ${AI_EMBEDDING_MODEL:text-embedding-3-small}

java-ai:
  enterprise-rag:
    model-name: ${AI_CHAT_MODEL:gpt-4o-mini}
    embedding-model-name: ${AI_EMBEDDING_MODEL:text-embedding-3-small}
